#define ACCESS_DENIED                    (unsigned int)0
#define BAD_EMAIL                        (unsigned int)1
#define BAD_EXPIRY_TIME                  (unsigned int)2
#define BAD_USERHOST_MASK                (unsigned int)3
#define CHAN_ACCESS_ADDED                (unsigned int)4
#define CHAN_ACCESS_COUNT                (unsigned int)5
#define CHAN_ACCESS_DELETED              (unsigned int)6
#define CHAN_ACCESS_DELETED_ONE          (unsigned int)7
#define CHAN_ACCESS_DELETED_SEVERAL      (unsigned int)8
#define CHAN_ACCESS_LEVEL_CHANGED        (unsigned int)9
#define CHAN_ACCESS_LEVEL_NONZERO        (unsigned int)10
#define CHAN_ACCESS_LEVEL_RANGE          (unsigned int)11
#define CHAN_ACCESS_LEVEL_UNCHANGED      (unsigned int)12
#define CHAN_ACCESS_LIST_EMPTY           (unsigned int)13
#define CHAN_ACCESS_LIST_FORMAT          (unsigned int)14
#define CHAN_ACCESS_LIST_HEADER          (unsigned int)15
#define CHAN_ACCESS_NICKS_ONLY           (unsigned int)16
#define CHAN_ACCESS_NOT_FOUND            (unsigned int)17
#define CHAN_ACCESS_NO_MATCH             (unsigned int)18
#define CHAN_ACCESS_NO_SUCH_ENTRY        (unsigned int)19
#define CHAN_ACCESS_REACHED_LIMIT        (unsigned int)20
#define CHAN_ACCESS_SYNTAX               (unsigned int)21
#define CHAN_AKICK_ADDED                 (unsigned int)22
#define CHAN_AKICK_ALREADY_EXISTS        (unsigned int)23
#define CHAN_AKICK_COUNT                 (unsigned int)24
#define CHAN_AKICK_DELETED               (unsigned int)25
#define CHAN_AKICK_DELETED_ONE           (unsigned int)26
#define CHAN_AKICK_DELETED_SEVERAL       (unsigned int)27
#define CHAN_AKICK_ENFORCE_DONE          (unsigned int)28
#define CHAN_AKICK_LIST_EMPTY            (unsigned int)29
#define CHAN_AKICK_LIST_FORMAT           (unsigned int)30
#define CHAN_AKICK_LIST_HEADER           (unsigned int)31
#define CHAN_AKICK_NO_MATCH              (unsigned int)32
#define CHAN_AKICK_REACHED_LIMIT         (unsigned int)33
#define CHAN_AKICK_SYNTAX                (unsigned int)34
#define CHAN_AKICK_VIEW_FORMAT1          (unsigned int)35
#define CHAN_AKICK_VIEW_FORMAT1_UNKNOWN  (unsigned int)36
#define CHAN_AKICK_VIEW_FORMAT2          (unsigned int)37
#define CHAN_AKICK_VIEW_FORMAT3          (unsigned int)38
#define CHAN_AKICK_VIEW_FORMAT4          (unsigned int)39
#define CHAN_AKICK_VIEW_FORMAT4_NEVER    (unsigned int)40
#define CHAN_AKICK_VIEW_FORMAT5          (unsigned int)41
#define CHAN_ALREADY_REGISTERED          (unsigned int)42
#define CHAN_CLEARED_BANS                (unsigned int)43
#define CHAN_CLEARED_MODES               (unsigned int)44
#define CHAN_CLEARED_OPS                 (unsigned int)45
#define CHAN_CLEARED_USERS               (unsigned int)46
#define CHAN_CLEARED_VOICES              (unsigned int)47
#define CHAN_CLEAR_SYNTAX                (unsigned int)48
#define CHAN_DEOP_SYNTAX                 (unsigned int)49
#define CHAN_DESC_CHANGED                (unsigned int)50
#define CHAN_DROPPED                     (unsigned int)51
#define CHAN_DROP_SYNTAX                 (unsigned int)52
#define CHAN_EMAIL_CHANGED               (unsigned int)53
#define CHAN_EMAIL_UNSET                 (unsigned int)54
#define CHAN_ENTRY_MSG_CHANGED           (unsigned int)55
#define CHAN_ENTRY_MSG_UNSET             (unsigned int)56
#define CHAN_EXCEEDED_CHANNEL_LIMIT      (unsigned int)57
#define CHAN_FORBID_FAILED               (unsigned int)58
#define CHAN_FORBID_SUCCEEDED            (unsigned int)59
#define CHAN_ALREADY_FORBIDDEN           (unsigned int)60
#define CHAN_FORBID_SYNTAX               (unsigned int)61
#define CHAN_FOUNDER_CHANGED             (unsigned int)62
#define CHAN_HELP                        (unsigned int)63
#define CHAN_HELP_ACCESS                 (unsigned int)64
#define CHAN_HELP_ACCESS_LEVELS          (unsigned int)65
#define CHAN_HELP_AKICK                  (unsigned int)66
#define CHAN_HELP_CLEAR                  (unsigned int)67
#define CHAN_HELP_DEOP                   (unsigned int)68
#define CHAN_HELP_DROP                   (unsigned int)69
#define CHAN_HELP_END                    (unsigned int)70
#define CHAN_HELP_EXPIRES                (unsigned int)71
#define CHAN_HELP_IDENTIFY               (unsigned int)72
#define CHAN_HELP_INFO                   (unsigned int)73
#define CHAN_HELP_INVITE                 (unsigned int)74
#define CHAN_HELP_LEVELS                 (unsigned int)75
#define CHAN_HELP_LEVELS_DESC            (unsigned int)76
#define CHAN_HELP_LEVELS_DESC_FORMAT     (unsigned int)77
#define CHAN_HELP_LIST                   (unsigned int)78
#define CHAN_HELP_OP                     (unsigned int)79
#define CHAN_HELP_REGISTER               (unsigned int)80
#define CHAN_HELP_SET                    (unsigned int)81
#define CHAN_HELP_SET_DESC               (unsigned int)82
#define CHAN_HELP_SET_EMAIL              (unsigned int)83
#define CHAN_HELP_SET_ENTRYMSG           (unsigned int)84
#define CHAN_HELP_SET_FOUNDER            (unsigned int)85
#define CHAN_HELP_SET_KEEPTOPIC          (unsigned int)86
#define CHAN_HELP_SET_LEAVEOPS           (unsigned int)87
#define CHAN_HELP_SET_MLOCK              (unsigned int)88
#define CHAN_HELP_SET_PASSWORD           (unsigned int)89
#define CHAN_HELP_SET_PRIVATE            (unsigned int)90
#define CHAN_HELP_SET_RESTRICTED         (unsigned int)91
#define CHAN_HELP_SET_SECURE             (unsigned int)92
#define CHAN_HELP_SET_SECUREOPS          (unsigned int)93
#define CHAN_HELP_SET_SUCCESSOR          (unsigned int)94
#define CHAN_HELP_SET_TOPIC              (unsigned int)95
#define CHAN_HELP_SET_TOPICLOCK          (unsigned int)96
#define CHAN_HELP_SET_URL                (unsigned int)97
#define CHAN_HELP_START                  (unsigned int)98
#define CHAN_HELP_UNBAN                  (unsigned int)99
#define CHAN_IDENTIFY_REQUIRED           (unsigned int)100
#define CHAN_IDENTIFY_SUCCEEDED          (unsigned int)101
#define CHAN_IDENTIFY_SYNTAX             (unsigned int)102
#define CHAN_INFO_DESCRIPTION            (unsigned int)103
#define CHAN_INFO_EMAIL                  (unsigned int)104
#define CHAN_INFO_ENTRYMSG               (unsigned int)105
#define CHAN_INFO_FOUNDER                (unsigned int)106
#define CHAN_INFO_HEADER                 (unsigned int)107
#define CHAN_INFO_LAST_TOPIC             (unsigned int)108
#define CHAN_INFO_LAST_USED              (unsigned int)109
#define CHAN_INFO_MODE_LOCK              (unsigned int)110
#define CHAN_INFO_NO_EXPIRE              (unsigned int)111
#define CHAN_INFO_NO_FOUNDER             (unsigned int)112
#define CHAN_INFO_NO_SUCCESSOR           (unsigned int)113
#define CHAN_INFO_OPTIONS                (unsigned int)114
#define CHAN_INFO_OPT_KEEPTOPIC          (unsigned int)115
#define CHAN_INFO_OPT_LEAVEOPS           (unsigned int)116
#define CHAN_INFO_OPT_NONE               (unsigned int)117
#define CHAN_INFO_OPT_PRIVATE            (unsigned int)118
#define CHAN_INFO_OPT_RESTRICTED         (unsigned int)119
#define CHAN_INFO_OPT_SECURE             (unsigned int)120
#define CHAN_INFO_OPT_SECUREOPS          (unsigned int)121
#define CHAN_INFO_OPT_TOPICLOCK          (unsigned int)122
#define CHAN_INFO_SUCCESSOR              (unsigned int)123
#define CHAN_INFO_SYNTAX                 (unsigned int)124
#define CHAN_INFO_TIME_REGGED            (unsigned int)125
#define CHAN_INFO_TOPIC_SET_BY           (unsigned int)126
#define CHAN_INFO_URL                    (unsigned int)127
#define CHAN_INVITE_SYNTAX               (unsigned int)128
#define CHAN_IS_REGISTERED               (unsigned int)129
#define CHAN_LEVELS_CHANGED              (unsigned int)130
#define CHAN_LEVELS_DISABLED             (unsigned int)131
#define CHAN_LEVELS_LIST_DISABLED        (unsigned int)132
#define CHAN_LEVELS_LIST_HEADER          (unsigned int)133
#define CHAN_LEVELS_LIST_NORMAL          (unsigned int)134
#define CHAN_LEVELS_RANGE                (unsigned int)135
#define CHAN_LEVELS_RESET                (unsigned int)136
#define CHAN_LEVELS_SYNTAX               (unsigned int)137
#define CHAN_LEVELS_UNKNOWN              (unsigned int)138
#define CHAN_LEVEL_ACCESS_CHANGE         (unsigned int)139
#define CHAN_LEVEL_ACCESS_LIST           (unsigned int)140
#define CHAN_LEVEL_AKICK                 (unsigned int)141
#define CHAN_LEVEL_AUTODEOP              (unsigned int)142
#define CHAN_LEVEL_AUTOOP                (unsigned int)143
#define CHAN_LEVEL_AUTOVOICE             (unsigned int)144
#define CHAN_LEVEL_CLEAR                 (unsigned int)145
#define CHAN_LEVEL_INVITE                (unsigned int)146
#define CHAN_LEVEL_MEMO_READ             (unsigned int)147
#define CHAN_LEVEL_MEMO_SEND             (unsigned int)148
#define CHAN_LEVEL_NOJOIN                (unsigned int)149
#define CHAN_LEVEL_OPDEOP                (unsigned int)150
#define CHAN_LEVEL_SET                   (unsigned int)151
#define CHAN_LEVEL_UNBAN                 (unsigned int)152
#define CHAN_LEVEL_SYNC                  (unsigned int)153
#define CHAN_LIST_END                    (unsigned int)154
#define CHAN_LIST_HEADER                 (unsigned int)155
#define CHAN_LIST_SERVADMIN_SYNTAX       (unsigned int)156
#define CHAN_LIST_SYNTAX                 (unsigned int)157
#define CHAN_MAY_NOT_BE_REGISTERED       (unsigned int)158
#define CHAN_MAY_NOT_BE_USED             (unsigned int)159
#define CHAN_MLOCK_CHANGED               (unsigned int)160
#define CHAN_MLOCK_REMOVED               (unsigned int)161
#define CHAN_MUST_BE_CHANOP              (unsigned int)162
#define CHAN_MUST_IDENTIFY_NICK          (unsigned int)163
#define CHAN_MUST_REGISTER_NICK          (unsigned int)164
#define CHAN_NOT_ALLOWED_TO_JOIN         (unsigned int)165
#define CHAN_OP_SYNTAX                   (unsigned int)166
#define CHAN_PASSWORD_CHANGED            (unsigned int)167
#define CHAN_PASSWORD_CHANGED_TO         (unsigned int)168
#define CHAN_PASSWORD_IS                 (unsigned int)169
#define CHAN_REACHED_CHANNEL_LIMIT       (unsigned int)170
#define CHAN_REGISTERED                  (unsigned int)171
#define CHAN_REGISTER_NOT_LOCAL          (unsigned int)172
#define CHAN_REGISTER_SYNTAX             (unsigned int)173
#define CHAN_REGISTRATION_FAILED         (unsigned int)174
#define CHAN_SERVADMIN_HELP              (unsigned int)175
#define CHAN_SERVADMIN_HELP_DROP         (unsigned int)176
#define CHAN_SERVADMIN_HELP_FORBID       (unsigned int)177
#define CHAN_SERVADMIN_HELP_INFO         (unsigned int)178
#define CHAN_SERVADMIN_HELP_LIST         (unsigned int)179
#define CHAN_SERVADMIN_HELP_SET          (unsigned int)180
#define CHAN_SERVADMIN_HELP_SET_NOEXPIRE (unsigned int)181
#define CHAN_SERVADMIN_HELP_STATUS       (unsigned int)182
#define CHAN_SET_FOUNDER_TOO_MANY_CHANS  (unsigned int)183
#define CHAN_SET_KEEPTOPIC_OFF           (unsigned int)184
#define CHAN_SET_KEEPTOPIC_ON            (unsigned int)185
#define CHAN_SET_KEEPTOPIC_SYNTAX        (unsigned int)186
#define CHAN_SET_LEAVEOPS_OFF            (unsigned int)187
#define CHAN_SET_LEAVEOPS_ON             (unsigned int)188
#define CHAN_SET_LEAVEOPS_SYNTAX         (unsigned int)189
#define CHAN_SET_MLOCK_KEY_REQUIRED      (unsigned int)190
#define CHAN_SET_MLOCK_LIMIT_POSITIVE    (unsigned int)191
#define CHAN_SET_MLOCK_LIMIT_REQUIRED    (unsigned int)192
#define CHAN_SET_MLOCK_UNKNOWN_CHAR      (unsigned int)193
#define CHAN_SET_NOEXPIRE_OFF            (unsigned int)194
#define CHAN_SET_NOEXPIRE_ON             (unsigned int)195
#define CHAN_SET_NOEXPIRE_SYNTAX         (unsigned int)196
#define CHAN_SET_PRIVATE_OFF             (unsigned int)197
#define CHAN_SET_PRIVATE_ON              (unsigned int)198
#define CHAN_SET_PRIVATE_SYNTAX          (unsigned int)199
#define CHAN_SET_RESTRICTED_OFF          (unsigned int)200
#define CHAN_SET_RESTRICTED_ON           (unsigned int)201
#define CHAN_SET_RESTRICTED_SYNTAX       (unsigned int)202
#define CHAN_SET_SECUREOPS_OFF           (unsigned int)203
#define CHAN_SET_SECUREOPS_ON            (unsigned int)204
#define CHAN_SET_SECUREOPS_SYNTAX        (unsigned int)205
#define CHAN_SET_SECURE_OFF              (unsigned int)206
#define CHAN_SET_SECURE_ON               (unsigned int)207
#define CHAN_SET_SECURE_SYNTAX           (unsigned int)208
#define CHAN_SET_SYNTAX                  (unsigned int)209
#define CHAN_SET_TOPICLOCK_OFF           (unsigned int)210
#define CHAN_SET_TOPICLOCK_ON            (unsigned int)211
#define CHAN_SET_TOPICLOCK_SYNTAX        (unsigned int)212
#define CHAN_SET_UNKNOWN_OPTION          (unsigned int)213
#define CHAN_SUCCESSOR_CHANGED           (unsigned int)214
#define CHAN_SUCCESSOR_IS_FOUNDER        (unsigned int)215
#define CHAN_SUCCESSOR_UNSET             (unsigned int)216
#define CHAN_UNBANNED                    (unsigned int)217
#define CHAN_UNBAN_SYNTAX                (unsigned int)218
#define CHAN_URL_CHANGED                 (unsigned int)219
#define CHAN_URL_UNSET                   (unsigned int)220
#define CHAN_X_FORBIDDEN                 (unsigned int)221
#define CHAN_X_NOT_IN_USE                (unsigned int)222
#define CHAN_X_NOT_REGISTERED            (unsigned int)223
#define COMMA_SPACE                      (unsigned int)224
#define FORCENICKCHANGE_IN_1_MINUTE      (unsigned int)225
#define FORCENICKCHANGE_IN_20_SECONDS    (unsigned int)226
#define FORCENICKCHANGE_NOW              (unsigned int)227
#define INFO_END                         (unsigned int)228
#define LANG_NAME                        (unsigned int)229
#define MEMO_AT_LIMIT                    (unsigned int)230
#define MEMO_CHAN_HEADER                 (unsigned int)231
#define MEMO_DELETED_NONE                (unsigned int)232
#define MEMO_DEL_SYNTAX                  (unsigned int)233
#define MEMO_HAVE_NEW_MEMO               (unsigned int)234
#define MEMO_HAVE_NEW_MEMOS              (unsigned int)235
#define MEMO_HAVE_NO_MEMOS               (unsigned int)236
#define MEMO_HAVE_NO_NEW_MEMOS           (unsigned int)237
#define MEMO_HEADER                      (unsigned int)238
#define MEMO_HELP                        (unsigned int)239
#define MEMO_HELP_DEL                    (unsigned int)240
#define MEMO_HELP_END                    (unsigned int)241
#define MEMO_HELP_INFO                   (unsigned int)242
#define MEMO_HELP_LIST                   (unsigned int)243
#define MEMO_HELP_READ                   (unsigned int)244
#define MEMO_HELP_SEND                   (unsigned int)245
#define MEMO_HELP_SET                    (unsigned int)246
#define MEMO_HELP_SET_LIMIT              (unsigned int)247
#define MEMO_HELP_SET_NOTIFY             (unsigned int)248
#define MEMO_HELP_START                  (unsigned int)249
#define MEMO_INFO_HARD_LIMIT             (unsigned int)250
#define MEMO_INFO_HARD_LIMIT_ZERO        (unsigned int)251
#define MEMO_INFO_LIMIT                  (unsigned int)252
#define MEMO_INFO_LIMIT_ZERO             (unsigned int)253
#define MEMO_INFO_MEMO                   (unsigned int)254
#define MEMO_INFO_MEMOS                  (unsigned int)255
#define MEMO_INFO_MEMOS_ALL_UNREAD       (unsigned int)256
#define MEMO_INFO_MEMOS_ONE_UNREAD       (unsigned int)257
#define MEMO_INFO_MEMOS_SOME_UNREAD      (unsigned int)258
#define MEMO_INFO_MEMO_UNREAD            (unsigned int)259
#define MEMO_INFO_NOTIFY_OFF             (unsigned int)260
#define MEMO_INFO_NOTIFY_ON              (unsigned int)261
#define MEMO_INFO_NOTIFY_RECEIVE         (unsigned int)262
#define MEMO_INFO_NOTIFY_SIGNON          (unsigned int)263
#define MEMO_INFO_NO_LIMIT               (unsigned int)264
#define MEMO_INFO_NO_MEMOS               (unsigned int)265
#define MEMO_INFO_X_HARD_LIMIT           (unsigned int)266
#define MEMO_INFO_X_LIMIT                (unsigned int)267
#define MEMO_INFO_X_MEMO                 (unsigned int)268
#define MEMO_INFO_X_MEMOS                (unsigned int)269
#define MEMO_INFO_X_MEMOS_ALL_UNREAD     (unsigned int)270
#define MEMO_INFO_X_MEMOS_ONE_UNREAD     (unsigned int)271
#define MEMO_INFO_X_MEMOS_SOME_UNREAD    (unsigned int)272
#define MEMO_INFO_X_MEMO_UNREAD          (unsigned int)273
#define MEMO_INFO_X_NOTIFY_OFF           (unsigned int)274
#define MEMO_INFO_X_NOTIFY_ON            (unsigned int)275
#define MEMO_INFO_X_NOTIFY_RECEIVE       (unsigned int)276
#define MEMO_INFO_X_NOTIFY_SIGNON        (unsigned int)277
#define MEMO_INFO_X_NO_LIMIT             (unsigned int)278
#define MEMO_INFO_X_NO_MEMOS             (unsigned int)279
#define MEMO_LIST_CHAN_MEMOS             (unsigned int)280
#define MEMO_LIST_CHAN_NEW_MEMOS         (unsigned int)281
#define MEMO_LIST_FORMAT                 (unsigned int)282
#define MEMO_LIST_HEADER                 (unsigned int)283
#define MEMO_LIST_MEMOS                  (unsigned int)284
#define MEMO_LIST_NEW_MEMOS              (unsigned int)285
#define MEMO_LIST_SYNTAX                 (unsigned int)286
#define MEMO_NEW_MEMO_ARRIVED            (unsigned int)287
#define MEMO_OVER_LIMIT                  (unsigned int)288
#define MEMO_READ_SYNTAX                 (unsigned int)289
#define MEMO_SEND_PLEASE_WAIT            (unsigned int)290
#define MEMO_SEND_SYNTAX                 (unsigned int)291
#define MEMO_SENT                        (unsigned int)292
#define MEMO_SERVADMIN_HELP_INFO         (unsigned int)293
#define MEMO_SERVADMIN_HELP_SET_LIMIT    (unsigned int)294
#define MEMO_SET_LIMIT                   (unsigned int)295
#define MEMO_SET_LIMIT_FORBIDDEN         (unsigned int)296
#define MEMO_SET_LIMIT_OVERFLOW          (unsigned int)297
#define MEMO_SET_LIMIT_SERVADMIN_SYNTAX  (unsigned int)298
#define MEMO_SET_LIMIT_SYNTAX            (unsigned int)299
#define MEMO_SET_LIMIT_TOO_HIGH          (unsigned int)300
#define MEMO_SET_LIMIT_ZERO              (unsigned int)301
#define MEMO_SET_NOTIFY_LOGON            (unsigned int)302
#define MEMO_SET_NOTIFY_NEW              (unsigned int)303
#define MEMO_SET_NOTIFY_OFF              (unsigned int)304
#define MEMO_SET_NOTIFY_ON               (unsigned int)305
#define MEMO_SET_NOTIFY_SYNTAX           (unsigned int)306
#define MEMO_SET_SYNTAX                  (unsigned int)307
#define MEMO_SET_UNKNOWN_OPTION          (unsigned int)308
#define MEMO_SET_YOUR_LIMIT              (unsigned int)309
#define MEMO_SET_YOUR_LIMIT_FORBIDDEN    (unsigned int)310
#define MEMO_SET_YOUR_LIMIT_TOO_HIGH     (unsigned int)311
#define MEMO_SET_YOUR_LIMIT_ZERO         (unsigned int)312
#define MEMO_TEXT                        (unsigned int)313
#define MEMO_TYPE_LIST_NEW               (unsigned int)314
#define MEMO_TYPE_READ_LAST              (unsigned int)315
#define MEMO_TYPE_READ_NUM               (unsigned int)316
#define MEMO_UNSET_LIMIT                 (unsigned int)317
#define MEMO_UNSET_YOUR_LIMIT            (unsigned int)318
#define MEMO_X_GETS_NO_MEMOS             (unsigned int)319
#define MEMO_X_HAS_NO_MEMOS              (unsigned int)320
#define MEMO_X_HAS_NO_NEW_MEMOS          (unsigned int)321
#define MEMO_X_HAS_TOO_MANY_MEMOS        (unsigned int)322
#define MORE_INFO                        (unsigned int)323
#define MORE_OBSCURE_PASSWORD            (unsigned int)324
#define NEED_EMAIL                       (unsigned int)325
#define NEWS_HELP_LOGON                  (unsigned int)326
#define NEWS_HELP_OPER                   (unsigned int)327
#define NEWS_LOGON_ADDED                 (unsigned int)328
#define NEWS_LOGON_ADD_FULL              (unsigned int)329
#define NEWS_LOGON_ADD_SYNTAX            (unsigned int)330
#define NEWS_LOGON_DELETED               (unsigned int)331
#define NEWS_LOGON_DELETED_ALL           (unsigned int)332
#define NEWS_LOGON_DEL_NONE              (unsigned int)333
#define NEWS_LOGON_DEL_NOT_FOUND         (unsigned int)334
#define NEWS_LOGON_DEL_SYNTAX            (unsigned int)335
#define NEWS_LOGON_LIST_ENTRY            (unsigned int)336
#define NEWS_LOGON_LIST_HEADER           (unsigned int)337
#define NEWS_LOGON_LIST_NONE             (unsigned int)338
#define NEWS_LOGON_SYNTAX                (unsigned int)339
#define NEWS_LOGON_TEXT                  (unsigned int)340
#define NEWS_OPER_ADDED                  (unsigned int)341
#define NEWS_OPER_ADD_FULL               (unsigned int)342
#define NEWS_OPER_ADD_SYNTAX             (unsigned int)343
#define NEWS_OPER_DELETED                (unsigned int)344
#define NEWS_OPER_DELETED_ALL            (unsigned int)345
#define NEWS_OPER_DEL_NONE               (unsigned int)346
#define NEWS_OPER_DEL_NOT_FOUND          (unsigned int)347
#define NEWS_OPER_DEL_SYNTAX             (unsigned int)348
#define NEWS_OPER_LIST_ENTRY             (unsigned int)349
#define NEWS_OPER_LIST_HEADER            (unsigned int)350
#define NEWS_OPER_LIST_NONE              (unsigned int)351
#define NEWS_OPER_SYNTAX                 (unsigned int)352
#define NEWS_OPER_TEXT                   (unsigned int)353
#define NICK_ACCESS_ADDED                (unsigned int)354
#define NICK_ACCESS_ALREADY_PRESENT      (unsigned int)355
#define NICK_ACCESS_DELETED              (unsigned int)356
#define NICK_ACCESS_LIST                 (unsigned int)357
#define NICK_ACCESS_LIST_X               (unsigned int)358
#define NICK_ACCESS_NOT_FOUND            (unsigned int)359
#define NICK_ACCESS_REACHED_LIMIT        (unsigned int)360
#define NICK_ACCESS_SYNTAX               (unsigned int)361
#define NICK_ALREADY_REGISTERED          (unsigned int)362
#define NICK_AUTOJOIN_ADDED              (unsigned int)363
#define NICK_AUTOJOIN_ALREADY_PRESENT    (unsigned int)364
#define NICK_AUTOJOIN_DELETED_ONE        (unsigned int)365
#define NICK_AUTOJOIN_DELETED_SEVERAL    (unsigned int)366
#define NICK_AUTOJOIN_LIST_FORMAT        (unsigned int)367
#define NICK_AUTOJOIN_LIST_HEADER        (unsigned int)368
#define NICK_AUTOJOIN_NO_MATCH           (unsigned int)369
#define NICK_AUTOJOIN_REACHED_LIMIT      (unsigned int)370
#define NICK_AUTOJOIN_SYNTAX             (unsigned int)371
#define NICK_BEG_SET_EMAIL               (unsigned int)372
#define NICK_CANNOT_BE_REGISTERED        (unsigned int)373
#define NICK_DROPPED                     (unsigned int)374
#define NICK_DROP_SYNTAX                 (unsigned int)375
#define NICK_FORBID_FAILED               (unsigned int)376
#define NICK_FORBID_SUCCEEDED            (unsigned int)377
#define NICK_FORBID_SYNTAX               (unsigned int)378
#define NICK_GHOST_KILLED                (unsigned int)379
#define NICK_GHOST_SYNTAX                (unsigned int)380
#define NICK_HELP                        (unsigned int)381
#define NICK_HELP_ACCESS                 (unsigned int)382
#define NICK_HELP_AUTOJOIN               (unsigned int)383
#define NICK_HELP_DROP                   (unsigned int)384
#define NICK_HELP_END                    (unsigned int)385
#define NICK_HELP_EXPIRE_ZERO            (unsigned int)386
#define NICK_HELP_GHOST                  (unsigned int)387
#define NICK_HELP_IDENTIFY               (unsigned int)388
#define NICK_HELP_INFO                   (unsigned int)389
#define NICK_HELP_LINK                   (unsigned int)390
#define NICK_HELP_LIST                   (unsigned int)391
#define NICK_HELP_RECOVER                (unsigned int)392
#define NICK_HELP_REGISTER               (unsigned int)393
#define NICK_HELP_RELEASE                (unsigned int)394
#define NICK_HELP_SENDPASS               (unsigned int)395
#define NICK_HELP_SET                    (unsigned int)396
#define NICK_HELP_SET_AUTOJOIN           (unsigned int)397
#define NICK_HELP_SET_EMAIL              (unsigned int)398
#define NICK_HELP_SET_HIDE               (unsigned int)399
#define NICK_HELP_SET_IRCOP              (unsigned int)400
#define NICK_HELP_SET_ENFORCE            (unsigned int)401
#define NICK_HELP_SET_LANGUAGE           (unsigned int)402
#define NICK_HELP_SET_NOOP               (unsigned int)403
#define NICK_HELP_SET_PASSWORD           (unsigned int)404
#define NICK_HELP_SET_PRIVATE            (unsigned int)405
#define NICK_HELP_SET_SECURE             (unsigned int)406
#define NICK_HELP_SET_URL                (unsigned int)407
#define NICK_HELP_START                  (unsigned int)408
#define NICK_HELP_STATUS                 (unsigned int)409
#define NICK_HELP_UNLINK                 (unsigned int)410
#define NICK_IDENTIFY_FAILED             (unsigned int)411
#define NICK_IDENTIFY_REQUIRED           (unsigned int)412
#define NICK_IDENTIFY_SUCCEEDED          (unsigned int)413
#define NICK_IDENTIFY_SYNTAX             (unsigned int)414
#define NICK_INFO_ADDRESS                (unsigned int)415
#define NICK_INFO_ADDRESS_ONLINE         (unsigned int)416
#define NICK_INFO_ADDRESS_ONLINE_NOHOST  (unsigned int)417
#define NICK_INFO_EMAIL                  (unsigned int)418
#define NICK_INFO_LAST_QUIT              (unsigned int)419
#define NICK_INFO_LAST_QUIT_TIME         (unsigned int)420
#define NICK_INFO_LAST_SEEN              (unsigned int)421
#define NICK_INFO_LINKED_TO              (unsigned int)422
#define NICK_INFO_NO_EXPIRE              (unsigned int)423
#define NICK_INFO_OPTIONS                (unsigned int)424
#define NICK_INFO_OPT_IRCOP              (unsigned int)425
#define NICK_INFO_OPT_ENFORCE            (unsigned int)426
#define NICK_INFO_OPT_MARKED             (unsigned int)427
#define NICK_INFO_OPT_NONE               (unsigned int)428
#define NICK_INFO_OPT_NOOP               (unsigned int)429
#define NICK_INFO_OPT_PRIVATE            (unsigned int)430
#define NICK_INFO_OPT_SECURE             (unsigned int)431
#define NICK_INFO_REALNAME               (unsigned int)432
#define NICK_INFO_SUSPEND_DETAILS        (unsigned int)433
#define NICK_INFO_SUSPEND_REASON         (unsigned int)434
#define NICK_INFO_SYNTAX                 (unsigned int)435
#define NICK_INFO_TIME_REGGED            (unsigned int)436
#define NICK_INFO_URL                    (unsigned int)437
#define NICK_IS_REGISTERED               (unsigned int)438
#define NICK_IS_SECURE                   (unsigned int)439
#define NICK_LINKED                      (unsigned int)440
#define NICK_LINK_DISABLED               (unsigned int)441
#define NICK_LINK_FAILED                 (unsigned int)442
#define NICK_LINK_SYNTAX                 (unsigned int)443
#define NICK_LISTLINKS_FOOTER            (unsigned int)444
#define NICK_LISTLINKS_HEADER            (unsigned int)445
#define NICK_LIST_HEADER                 (unsigned int)446
#define NICK_LIST_RESULTS                (unsigned int)447
#define NICK_LIST_SERVADMIN_SYNTAX       (unsigned int)448
#define NICK_LIST_SYNTAX                 (unsigned int)449
#define NICK_MAY_NOT_BE_USED             (unsigned int)450
#define NICK_NOT_IRCOP                   (unsigned int)451
#define NICK_NOT_LINKED                  (unsigned int)452
#define NICK_NOT_REGISTERED              (unsigned int)453
#define NICK_NOT_REGISTERED_HELP         (unsigned int)454
#define NICK_NO_GHOST_SELF               (unsigned int)455
#define NICK_NO_LINK_SAME                (unsigned int)456
#define NICK_NO_RECOVER_SELF             (unsigned int)457
#define NICK_PASSWORD_IS                 (unsigned int)458
#define NICK_RECOVERED                   (unsigned int)459
#define NICK_RECOVER_SYNTAX              (unsigned int)460
#define NICK_REGISTERED                  (unsigned int)461
#define NICK_REGISTER_NEWNICK            (unsigned int)462
#define NICK_REGISTER_AUTH_SYNTAX        (unsigned int)463
#define NICK_REGISTER_SYNTAX             (unsigned int)464
#define NICK_REGISTRATION_FAILED         (unsigned int)465
#define NICK_REG_PLEASE_WAIT             (unsigned int)466
#define NICK_RELEASED                    (unsigned int)467
#define NICK_RELEASE_NOT_HELD            (unsigned int)468
#define NICK_RELEASE_SYNTAX              (unsigned int)469
#define NICK_SERVADMIN_HELP              (unsigned int)470
#define NICK_SERVADMIN_HELP_DROP         (unsigned int)471
#define NICK_SERVADMIN_HELP_FORBID       (unsigned int)472
#define NICK_SERVADMIN_HELP_INFO         (unsigned int)473
#define NICK_SERVADMIN_HELP_LIST         (unsigned int)474
#define NICK_SERVADMIN_HELP_LISTLINKS    (unsigned int)475
#define NICK_SERVADMIN_HELP_SET          (unsigned int)476
#define NICK_SERVADMIN_HELP_SET_MARK     (unsigned int)477
#define NICK_SERVADMIN_HELP_SET_NOEXPIRE (unsigned int)478
#define NICK_SERVADMIN_HELP_SUSPEND      (unsigned int)479
#define NICK_SERVADMIN_HELP_UNLINK       (unsigned int)480
#define NICK_SERVADMIN_HELP_UNSUSPEND    (unsigned int)481
#define NICK_SET_AUTOJOIN_OFF            (unsigned int)482
#define NICK_SET_AUTOJOIN_ON             (unsigned int)483
#define NICK_SET_AUTOJOIN_SYNTAX         (unsigned int)484
#define NICK_SET_EMAIL_CHANGED           (unsigned int)485
#define NICK_SET_EMAIL_MANDATORY         (unsigned int)486
#define NICK_SET_EMAIL_UNCHANGED         (unsigned int)487
#define NICK_SET_HIDE_EMAIL_OFF          (unsigned int)488
#define NICK_SET_HIDE_EMAIL_ON           (unsigned int)489
#define NICK_SET_HIDE_MASK_OFF           (unsigned int)490
#define NICK_SET_HIDE_MASK_ON            (unsigned int)491
#define NICK_SET_HIDE_QUIT_OFF           (unsigned int)492
#define NICK_SET_HIDE_QUIT_ON            (unsigned int)493
#define NICK_SET_HIDE_SYNTAX             (unsigned int)494
#define NICK_SET_IRCOP_ON                (unsigned int)495
#define NICK_SET_IRCOP_OFF               (unsigned int)496
#define NICK_SET_IRCOP_SYNTAX            (unsigned int)497
#define NICK_SET_MARK_SYNTAX             (unsigned int)498
#define NICK_SET_MARK_ON                 (unsigned int)499
#define NICK_SET_MARK_OFF                (unsigned int)500
#define NICK_SET_ENFORCE_OFF             (unsigned int)501
#define NICK_SET_ENFORCE_ON              (unsigned int)502
#define NICK_SET_ENFORCE_QUICK           (unsigned int)503
#define NICK_SET_ENFORCE_SYNTAX          (unsigned int)504
#define NICK_SET_LANGUAGE_CHANGED        (unsigned int)505
#define NICK_SET_LANGUAGE_SYNTAX         (unsigned int)506
#define NICK_SET_LANGUAGE_UNKNOWN        (unsigned int)507
#define NICK_SET_NOEXPIRE_OFF            (unsigned int)508
#define NICK_SET_NOEXPIRE_ON             (unsigned int)509
#define NICK_SET_NOEXPIRE_SYNTAX         (unsigned int)510
#define NICK_SET_NOOP_OFF                (unsigned int)511
#define NICK_SET_NOOP_ON                 (unsigned int)512
#define NICK_SET_NOOP_SYNTAX             (unsigned int)513
#define NICK_SET_PASSWORD_CHANGED        (unsigned int)514
#define NICK_SET_PASSWORD_CHANGED_TO     (unsigned int)515
#define NICK_SET_PRIVATE_OFF             (unsigned int)516
#define NICK_SET_PRIVATE_ON              (unsigned int)517
#define NICK_SET_PRIVATE_SYNTAX          (unsigned int)518
#define NICK_SET_SECURE_OFF              (unsigned int)519
#define NICK_SET_SECURE_ON               (unsigned int)520
#define NICK_SET_SECURE_SYNTAX           (unsigned int)521
#define NICK_SET_SERVADMIN_SYNTAX        (unsigned int)522
#define NICK_SET_SYNTAX                  (unsigned int)523
#define NICK_SET_UNKNOWN_OPTION          (unsigned int)524
#define NICK_SET_UNKNOWN_OPTION_OR_BAD_NICK (unsigned int)525
#define NICK_SET_URL_CHANGED             (unsigned int)526
#define NICK_SET_URL_UNSET               (unsigned int)527
#define NICK_SUSPEND_ALREADY_SUSPENDED   (unsigned int)528
#define NICK_SUSPEND_NOT_SUSPENDED       (unsigned int)529
#define NICK_SUSPEND_SUCCEEDED           (unsigned int)530
#define NICK_SUSPEND_SYNTAX              (unsigned int)531
#define NICK_UNLINKED                    (unsigned int)532
#define NICK_UNLINK_FAILED               (unsigned int)533
#define NICK_UNLINK_SYNTAX               (unsigned int)534
#define NICK_UNSUSPEND_SUCCEEDED         (unsigned int)535
#define NICK_UNSUSPEND_SYNTAX            (unsigned int)536
#define NICK_X_DROPPED                   (unsigned int)537
#define NICK_X_FORBIDDEN                 (unsigned int)538
#define NICK_X_HAS_LINKS                 (unsigned int)539
#define NICK_X_IS_LINKED                 (unsigned int)540
#define NICK_X_MARKED                    (unsigned int)541
#define NICK_X_NOOP                      (unsigned int)542
#define NICK_X_NOT_IN_USE                (unsigned int)543
#define NICK_X_NOT_LINKED                (unsigned int)544
#define NICK_X_NOT_REGISTERED            (unsigned int)545
#define NICK_X_SUSPENDED                 (unsigned int)546
#define NICK_X_UNLINKED                  (unsigned int)547
#define NO_HELP_AVAILABLE                (unsigned int)548
#define OPER_ADMIN_ADDED                 (unsigned int)549
#define OPER_ADMIN_ADD_SYNTAX            (unsigned int)550
#define OPER_ADMIN_DEL_SYNTAX            (unsigned int)551
#define OPER_ADMIN_EXISTS                (unsigned int)552
#define OPER_ADMIN_LIST_HEADER           (unsigned int)553
#define OPER_ADMIN_NOT_FOUND             (unsigned int)554
#define OPER_ADMIN_REMOVED               (unsigned int)555
#define OPER_ADMIN_SYNTAX                (unsigned int)556
#define OPER_ADMIN_TOO_MANY              (unsigned int)557
#define OPER_AKILL_ADDED                 (unsigned int)558
#define OPER_AKILL_ADD_SYNTAX            (unsigned int)559
#define OPER_AKILL_COUNT                 (unsigned int)560
#define OPER_AKILL_DEL_SYNTAX            (unsigned int)561
#define OPER_AKILL_EXPIRES_1D            (unsigned int)562
#define OPER_AKILL_EXPIRES_1H1M          (unsigned int)563
#define OPER_AKILL_EXPIRES_1HM           (unsigned int)564
#define OPER_AKILL_EXPIRES_1M            (unsigned int)565
#define OPER_AKILL_EXPIRES_D             (unsigned int)566
#define OPER_AKILL_EXPIRES_H1M           (unsigned int)567
#define OPER_AKILL_EXPIRES_HM            (unsigned int)568
#define OPER_AKILL_EXPIRES_M             (unsigned int)569
#define OPER_AKILL_EXPIRES_SOON          (unsigned int)570
#define OPER_AKILL_LIST_FORMAT           (unsigned int)571
#define OPER_AKILL_LIST_HEADER           (unsigned int)572
#define OPER_AKILL_MASK_TOO_GENERAL      (unsigned int)573
#define OPER_AKILL_NOT_FOUND             (unsigned int)574
#define OPER_AKILL_NO_EXPIRE             (unsigned int)575
#define OPER_AKILL_NO_NICK               (unsigned int)576
#define OPER_AKILL_REMOVED               (unsigned int)577
#define OPER_AKILL_SYNTAX                (unsigned int)578
#define OPER_AKILL_VIEW_FORMAT           (unsigned int)579
#define OPER_BOUNCY_MODES                (unsigned int)580
#define OPER_BOUNCY_MODES_U_LINE         (unsigned int)581
#define OPER_CANNOT_RESTART              (unsigned int)582
#define OPER_CLEARMODES_ALL_DONE         (unsigned int)583
#define OPER_CLEARMODES_DONE             (unsigned int)584
#define OPER_CLEARMODES_SYNTAX           (unsigned int)585
#define OPER_EXCEPTION_ADDED             (unsigned int)586
#define OPER_EXCEPTION_ADD_SYNTAX        (unsigned int)587
#define OPER_EXCEPTION_ALREADY_PRESENT   (unsigned int)588
#define OPER_EXCEPTION_DELETED           (unsigned int)589
#define OPER_EXCEPTION_DELETED_ONE       (unsigned int)590
#define OPER_EXCEPTION_DELETED_SEVERAL   (unsigned int)591
#define OPER_EXCEPTION_DEL_SYNTAX        (unsigned int)592
#define OPER_EXCEPTION_DISABLED          (unsigned int)593
#define OPER_EXCEPTION_INVALID_HOSTMASK  (unsigned int)594
#define OPER_EXCEPTION_INVALID_LIMIT     (unsigned int)595
#define OPER_EXCEPTION_LIST_COLHEAD      (unsigned int)596
#define OPER_EXCEPTION_LIST_FORMAT       (unsigned int)597
#define OPER_EXCEPTION_LIST_HEADER       (unsigned int)598
#define OPER_EXCEPTION_NO_MATCH          (unsigned int)599
#define OPER_EXCEPTION_SYNTAX            (unsigned int)600
#define OPER_EXCEPTION_TOO_MANY          (unsigned int)601
#define OPER_EXCEPTION_VIEW_FORMAT       (unsigned int)602
#define OPER_GLOBAL_SYNTAX               (unsigned int)603
#define OPER_HELP                        (unsigned int)604
#define OPER_HELP_ADMIN                  (unsigned int)605
#define OPER_HELP_AKILL                  (unsigned int)606
#define OPER_HELP_CLEARMODES             (unsigned int)607
#define OPER_HELP_END                    (unsigned int)608
#define OPER_HELP_EXCEPTION              (unsigned int)609
#define OPER_HELP_GLOBAL                 (unsigned int)610
#define OPER_HELP_JUPE                   (unsigned int)611
#define OPER_HELP_KICK                   (unsigned int)612
#define OPER_HELP_KILLCLONES             (unsigned int)613
#define OPER_HELP_MODE                   (unsigned int)614
#define OPER_HELP_OPER                   (unsigned int)615
#define OPER_HELP_QUARANTINE             (unsigned int)616
#define OPER_HELP_QUIT                   (unsigned int)617
#define OPER_HELP_RAW                    (unsigned int)618
#define OPER_HELP_RESTART                (unsigned int)619
#define OPER_HELP_ROTATELOG              (unsigned int)620
#define OPER_HELP_SESSION                (unsigned int)621
#define OPER_HELP_SET                    (unsigned int)622
#define OPER_HELP_SET_DEBUG              (unsigned int)623
#define OPER_HELP_SET_LOGSQL             (unsigned int)624
#define OPER_HELP_SHUTDOWN               (unsigned int)625
#define OPER_HELP_START                  (unsigned int)626
#define OPER_HELP_STATS                  (unsigned int)627
#define OPER_IGNORE_LIST                 (unsigned int)628
#define OPER_IGNORE_LIST_EMPTY           (unsigned int)629
#define OPER_JUPE_SYNTAX                 (unsigned int)630
#define OPER_KICK_SYNTAX                 (unsigned int)631
#define OPER_KILLCLONES_SYNTAX           (unsigned int)632
#define OPER_KILLCLONES_UNKNOWN_NICK     (unsigned int)633
#define OPER_MODE_SYNTAX                 (unsigned int)634
#define OPER_OPER_ADDED                  (unsigned int)635
#define OPER_OPER_ADD_SYNTAX             (unsigned int)636
#define OPER_OPER_DEL_SYNTAX             (unsigned int)637
#define OPER_OPER_EXISTS                 (unsigned int)638
#define OPER_OPER_LIST_HEADER            (unsigned int)639
#define OPER_OPER_NOT_FOUND              (unsigned int)640
#define OPER_OPER_REMOVED                (unsigned int)641
#define OPER_OPER_SYNTAX                 (unsigned int)642
#define OPER_OPER_TOO_MANY               (unsigned int)643
#define OPER_QUARANTINE_ADDED            (unsigned int)644
#define OPER_QUARANTINE_ALREADY_PRESENT  (unsigned int)645
#define OPER_QUARANTINE_CHAN_MATCHES     (unsigned int)646
#define OPER_QUARANTINE_CHAN_MATCHES_ONE (unsigned int)647
#define OPER_QUARANTINE_DELETED_ONE      (unsigned int)648
#define OPER_QUARANTINE_DELETED_SEVERAL  (unsigned int)649
#define OPER_QUARANTINE_LIST_FORMAT1     (unsigned int)650
#define OPER_QUARANTINE_LIST_FORMAT2     (unsigned int)651
#define OPER_QUARANTINE_LIST_HEADER      (unsigned int)652
#define OPER_QUARANTINE_NICK_MATCHES     (unsigned int)653
#define OPER_QUARANTINE_NICK_MATCHES_ONE (unsigned int)654
#define OPER_QUARANTINE_NO_MATCH         (unsigned int)655
#define OPER_QUARANTINE_BROKEN_REGEX     (unsigned int)656
#define OPER_QUARANTINE_SYNTAX           (unsigned int)657
#define OPER_RAW_SYNTAX                  (unsigned int)658
#define OPER_ROTATELOG_FILE_EXISTS       (unsigned int)659
#define OPER_ROTATELOG_OPEN_LOG_FAIL     (unsigned int)660
#define OPER_ROTATELOG_RENAME_DONE       (unsigned int)661
#define OPER_ROTATELOG_RENAME_FAIL       (unsigned int)662
#define OPER_SESSION_DISABLED            (unsigned int)663
#define OPER_SESSION_INVALID_THRESHOLD   (unsigned int)664
#define OPER_SESSION_LIST_COLHEAD        (unsigned int)665
#define OPER_SESSION_LIST_FORMAT         (unsigned int)666
#define OPER_SESSION_LIST_HEADER         (unsigned int)667
#define OPER_SESSION_LIST_SYNTAX         (unsigned int)668
#define OPER_SESSION_NOT_FOUND           (unsigned int)669
#define OPER_SESSION_SYNTAX              (unsigned int)670
#define OPER_SESSION_VIEW_FORMAT         (unsigned int)671
#define OPER_SESSION_VIEW_SYNTAX         (unsigned int)672
#define OPER_SET_DEBUG_ERROR             (unsigned int)673
#define OPER_SET_DEBUG_LEVEL             (unsigned int)674
#define OPER_SET_DEBUG_OFF               (unsigned int)675
#define OPER_SET_DEBUG_ON                (unsigned int)676
#define OPER_SET_LOGSQL_ON               (unsigned int)677
#define OPER_SET_LOGSQL_OFF              (unsigned int)678
#define OPER_SET_LOGSQL_ERROR            (unsigned int)679
#define OPER_SET_IGNORE_ERROR            (unsigned int)680
#define OPER_SET_IGNORE_OFF              (unsigned int)681
#define OPER_SET_IGNORE_ON               (unsigned int)682
#define OPER_SET_SYNTAX                  (unsigned int)683
#define OPER_SET_UNKNOWN_OPTION          (unsigned int)684
#define OPER_STATS_AKILL_COUNT           (unsigned int)685
#define OPER_STATS_AKILL_EXPIRE_DAY      (unsigned int)686
#define OPER_STATS_AKILL_EXPIRE_DAYS     (unsigned int)687
#define OPER_STATS_AKILL_EXPIRE_HOUR     (unsigned int)688
#define OPER_STATS_AKILL_EXPIRE_HOURS    (unsigned int)689
#define OPER_STATS_AKILL_EXPIRE_MIN      (unsigned int)690
#define OPER_STATS_AKILL_EXPIRE_MINS     (unsigned int)691
#define OPER_STATS_AKILL_EXPIRE_NONE     (unsigned int)692
#define OPER_STATS_BYTES_READ            (unsigned int)693
#define OPER_STATS_BYTES_WRITTEN         (unsigned int)694
#define OPER_STATS_CHANNEL_MEM           (unsigned int)695
#define OPER_STATS_CHANSERV_MEM          (unsigned int)696
#define OPER_STATS_CURRENT_USERS         (unsigned int)697
#define OPER_STATS_MAX_USERS             (unsigned int)698
#define OPER_STATS_NICKSERV_MEM          (unsigned int)699
#define OPER_STATS_OPERSERV_MEM          (unsigned int)700
#define OPER_STATS_SERVER_MEM            (unsigned int)701
#define OPER_STATS_SESSIONS_MEM          (unsigned int)702
#define OPER_STATS_UNKNOWN_OPTION        (unsigned int)703
#define OPER_STATS_UPTIME_1DHMS          (unsigned int)704
#define OPER_STATS_UPTIME_1H1M1S         (unsigned int)705
#define OPER_STATS_UPTIME_1H1MS          (unsigned int)706
#define OPER_STATS_UPTIME_1HM1S          (unsigned int)707
#define OPER_STATS_UPTIME_1HMS           (unsigned int)708
#define OPER_STATS_UPTIME_1M1S           (unsigned int)709
#define OPER_STATS_UPTIME_1MS            (unsigned int)710
#define OPER_STATS_UPTIME_DHMS           (unsigned int)711
#define OPER_STATS_UPTIME_H1M1S          (unsigned int)712
#define OPER_STATS_UPTIME_H1MS           (unsigned int)713
#define OPER_STATS_UPTIME_HM1S           (unsigned int)714
#define OPER_STATS_UPTIME_HMS            (unsigned int)715
#define OPER_STATS_UPTIME_M1S            (unsigned int)716
#define OPER_STATS_UPTIME_MS             (unsigned int)717
#define OPER_STATS_USER_MEM              (unsigned int)718
#define OPER_TOO_MANY_AKILLS             (unsigned int)719
#define PASSWORD_INCORRECT               (unsigned int)720
#define PASSWORD_TRUNCATED               (unsigned int)721
#define PERMISSION_DENIED                (unsigned int)722
#define STRFTIME_DATE_TIME_FORMAT        (unsigned int)723
#define STRFTIME_DAYS_LONG               (unsigned int)724
#define STRFTIME_DAYS_SHORT              (unsigned int)725
#define STRFTIME_MONTHS_LONG             (unsigned int)726
#define STRFTIME_MONTHS_SHORT            (unsigned int)727
#define STRFTIME_SHORT_DATE_FORMAT       (unsigned int)728
#define SYNTAX_ERROR                     (unsigned int)729
#define UNKNOWN_COMMAND                  (unsigned int)730
#define UNKNOWN_COMMAND_HELP             (unsigned int)731
#define USER_RECORD_NOT_FOUND            (unsigned int)732
#define SENDPASS_UNAVAILABLE             (unsigned int)733
#define NICK_SENDPASS_SYNTAX             (unsigned int)734
#define NICK_X_HAS_NO_EMAIL              (unsigned int)735
#define NICK_SENDPASS_MAIL               (unsigned int)736
#define SENDPASS_FAILED                  (unsigned int)737
#define NICK_X_SENDPASSED                (unsigned int)738
#define CHAN_HELP_SENDPASS               (unsigned int)739
#define CHAN_SENDPASS_SYNTAX             (unsigned int)740
#define CHAN_X_HAS_NO_EMAIL              (unsigned int)741
#define CHAN_X_SENDPASSED                (unsigned int)742
#define CHAN_SENDPASS_MAIL               (unsigned int)743
#define NICK_ACCESS_NO_MATCH             (unsigned int)744
#define NICK_ACCESS_DELETED_ONE          (unsigned int)745
#define NICK_ACCESS_DELETED_SEVERAL      (unsigned int)746
#define CHAN_HELP_VOICE                  (unsigned int)747
#define CHAN_HELP_DEVOICE                (unsigned int)748
#define CHAN_HELP_SYNC                   (unsigned int)749
#define CHAN_SYNC_SYNTAX                 (unsigned int)750
#define CHAN_VOICE_SYNTAX                (unsigned int)751
#define CHAN_DEVOICE_SYNTAX              (unsigned int)752
#define CHAN_VOP_SYNTAX                  (unsigned int)753
#define CHAN_AOP_SYNTAX                  (unsigned int)754
#define CHAN_SOP_SYNTAX                  (unsigned int)755
#define CHAN_VOP_DISABLED                (unsigned int)756
#define CHAN_AOP_DISABLED                (unsigned int)757
#define CHAN_SOP_DISABLED                (unsigned int)758
#define CHAN_HELP_VOP                    (unsigned int)759
#define CHAN_HELP_AOP                    (unsigned int)760
#define CHAN_HELP_SOP                    (unsigned int)761
#define CHAN_LEVEL_LEVEL_LIST            (unsigned int)762
#define CHAN_LEVEL_LEVEL_CHANGE          (unsigned int)763
#define NICK_REGAIN_SYNTAX               (unsigned int)764
#define NICK_NO_REGAIN_SELF              (unsigned int)765
#define NICK_REGAIN_REGAINED             (unsigned int)766
#define NICK_HELP_REGAIN                 (unsigned int)767
#define MEMO_SERVADMIN_HELP              (unsigned int)768
#define MEMO_SERVADMIN_HELP_GLOBALSEND   (unsigned int)769
#define MEMO_SERVADMIN_HELP_OPERSEND     (unsigned int)770
#define MEMO_SERVADMIN_HELP_CSOPSEND     (unsigned int)771
#define MEMO_GLOBALSEND_SERVADMIN_SYNTAX (unsigned int)772
#define MEMO_OPERSEND_SERVADMIN_SYNTAX   (unsigned int)773
#define MEMO_CSOPSEND_SERVADMIN_SYNTAX   (unsigned int)774
#define MEMO_SERVADMIN_GLOBALSENT        (unsigned int)775
#define MEMO_SERVADMIN_OPERSENT          (unsigned int)776
#define MEMO_SERVADMIN_CSOPSENT          (unsigned int)777
#define MEMO_GLOBAL_TEXT                 (unsigned int)778
#define MEMO_OPER_TEXT                   (unsigned int)779
#define MEMO_CSOP_TEXT                   (unsigned int)780
#define NICK_HELP_LISTLINKS              (unsigned int)781
#define NICK_HELP_LISTCHANS              (unsigned int)782
#define NICK_SERVADMIN_HELP_LISTCHANS    (unsigned int)783
#define NICK_LISTCHANS_FOUNDER_HEADER    (unsigned int)784
#define NICK_X_IS_FOUNDER                (unsigned int)785
#define NICK_LISTCHANS_ACCESS_HEADER     (unsigned int)786
#define NICK_X_HAS_ACCESS                (unsigned int)787
#define NICK_LISTCHANS_FOOTER            (unsigned int)788
#define OPER_STATS_MEMOSERV_MEM          (unsigned int)789
#define NICK_LINK_TOO_MANY_CHANNELS      (unsigned int)790
#define NICK_INFO_SHOW_ALL               (unsigned int)791
#define CHAN_HELP_SET_VERBOSE            (unsigned int)792
#define CHAN_SET_VERBOSE_ON              (unsigned int)793
#define CHAN_SET_VERBOSE_OFF             (unsigned int)794
#define CHAN_SET_VERBOSE_SYNTAX          (unsigned int)795
#define CHAN_INFO_OPT_VERBOSE            (unsigned int)796
#define CHAN_ACCESS_VIEW_HEADER          (unsigned int)797
#define CHAN_ACCESS_VIEW_FORMAT1         (unsigned int)798
#define CHAN_ACCESS_VIEW_FORMAT2         (unsigned int)799
#define CHAN_ACCESS_VIEW_FORMAT2_NOMODIFY (unsigned int)800
#define CHAN_ACCESS_VIEW_FORMAT3         (unsigned int)801
#define CHAN_ACCESS_VIEW_FORMAT4         (unsigned int)802
#define CHAN_ACCESS_VIEW_FORMAT5         (unsigned int)803
#define CHAN_ACCESS_VIEW_FORMAT5_NEVER_USED (unsigned int)804
#define CHAN_HAS_NEW_MEMOS               (unsigned int)805
#define MEMO_NEW_CHAN_MEMO_ARRIVED       (unsigned int)806
#define CHAN_LEVEL_AKICK_LIST            (unsigned int)807
#define OPER_AKILL_TOO_MANY_MATCHES      (unsigned int)808
#define OPER_AKILL_TOO_LONG              (unsigned int)809
#define OPER_AKILL_MASK_TOO_GENERAL_FORCE (unsigned int)810
#define OPER_AKILL_ONLY_DELETE_OWN       (unsigned int)811
#define NICK_SERVADMIN_HELP_SET_REGTIME  (unsigned int)812
#define NICK_SET_REGTIME_SYNTAX          (unsigned int)813
#define NICK_SET_REGTIME                 (unsigned int)814
#define CHAN_HELP_SET_AUTOLIMIT          (unsigned int)815
#define CHAN_SET_AUTOLIMIT_SYNTAX        (unsigned int)816
#define CHAN_SET_AUTOLIMIT_DISABLED      (unsigned int)817
#define CHAN_SET_AUTOLIMIT_CHANGED       (unsigned int)818
#define CHAN_INFO_AUTOLIMIT              (unsigned int)819
#define CHAN_SET_AUTOLIMIT_BAD_TOLERANCE (unsigned int)820
#define CHAN_HELP_SET_CLEARBANS          (unsigned int)821
#define CHAN_SET_CLEARBANS_SYNTAX        (unsigned int)822
#define CHAN_SET_CLEARBANS_OFF           (unsigned int)823
#define CHAN_SET_CLEARBANS_CHANGED       (unsigned int)824
#define CHAN_INFO_CLEARBANS              (unsigned int)825
#define CHAN_SET_MLOCK_SYNTAX            (unsigned int)826
#define CHAN_SERVADMIN_HELP_SET_REGTIME  (unsigned int)827
#define CHAN_SET_REGTIME_SYNTAX          (unsigned int)828
#define CHAN_SET_REGTIME                 (unsigned int)829
#define OPER_AKILL_MASK_ALREADY_AKILLED  (unsigned int)830
#define NICK_X_IS_LINK                   (unsigned int)831
#define BAD_PASS_NICK_NAME               (unsigned int)832
#define BAD_PASS_USERNAME                (unsigned int)833
#define BAD_PASS_REALNAME                (unsigned int)834
#define BAD_PASS_NICK_OR_LINK            (unsigned int)835
#define BAD_PASS_CHANNEL_NAME            (unsigned int)836
#define BAD_PASS_WAY_TOO_SHORT           (unsigned int)837
#define BAD_PASS_TOO_SHORT               (unsigned int)838
#define BAD_PASS_NOT_ENOUGH_DIFF         (unsigned int)839
#define BAD_PASS_TOO_SIMPLISTIC          (unsigned int)840
#define BAD_PASS_NAT_INS                 (unsigned int)841
#define BAD_PASS_DICT_WORD               (unsigned int)842
#define BAD_PASS_REV_DICT_WORD           (unsigned int)843
#define NICK_REG_NO_SUCH_AUTH            (unsigned int)844
#define NICK_REG_AUTH_MAIL               (unsigned int)845
#define NICK_REG_AUTH_MAILED             (unsigned int)846
#define NICK_ALREADY_PART_REGISTERED     (unsigned int)847
#define NICK_DROP_NO_SUCH_AUTH           (unsigned int)848
#define NICK_ALREADY_PART_DROPPED        (unsigned int)849
#define NICK_DROP_AUTH_MAIL              (unsigned int)850
#define NICK_DROP_AUTH_MAILED            (unsigned int)851
#define NICK_SENDPASS_NO_SUCH_AUTH       (unsigned int)852
#define NICK_SENDPASS_ALREADY_REQUESTED  (unsigned int)853
#define NICK_SENDPASS_AUTH_MAIL          (unsigned int)854
#define NICK_SENDPASS_AUTH_MAILED        (unsigned int)855
#define NICK_HELP_SET_SENDPASS           (unsigned int)856
#define NICK_SET_SENDPASS_SYNTAX         (unsigned int)857
#define NICK_SET_SENDPASS_ON             (unsigned int)858
#define NICK_SET_SENDPASS_OFF            (unsigned int)859
#define NICK_INFO_OPT_NOSENDPASS         (unsigned int)860
#define NICK_X_DISABLED_SENDPASS         (unsigned int)861
#define CHAN_OP_NICK_NOT_PRESENT         (unsigned int)862
#define CHAN_SENDPASS_NO_SUCH_AUTH       (unsigned int)863
#define CHAN_SENDPASS_AUTH_MAIL          (unsigned int)864
#define CHAN_SENDPASS_ALREADY_REQUESTED  (unsigned int)865
#define CHAN_SENDPASS_AUTH_MAILED        (unsigned int)866
#define MEMO_DELETED_X                   (unsigned int)867
#define WARN_BAD_PASS                    (unsigned int)868
#define OPER_HELP_LOADLANGS              (unsigned int)869
#define OPER_LOADLANGS_RELOADED          (unsigned int)870
#define CHAN_HELP_SET_FLOODSERV          (unsigned int)871
#define FLOOD_HELP                       (unsigned int)872
#define FLOOD_HELP_CHAN                  (unsigned int)873
#define FLOOD_HELP_SET                   (unsigned int)874
#define NICK_HELP_SET_CLOAK              (unsigned int)875
#define NICK_SET_CLOAK_OFF               (unsigned int)876
#define NICK_SET_CLOAK_ON                (unsigned int)877
#define NICK_SET_CLOAK_SYNTAX            (unsigned int)878
#define NICK_SERVADMIN_HELP_SET_CLOAKSTRING (unsigned int)879
#define NICK_SET_CLOAKSTRING_SYNTAX      (unsigned int)880
#define NICK_SET_CLOAKSTRING             (unsigned int)881
#define CHAN_SERVADMIN_HELP_SET_CLOAK    (unsigned int)882
#define CHAN_SET_CLOAK_SYNTAX            (unsigned int)883
#define CHAN_SET_CLOAK                   (unsigned int)884
#define CHAN_SET_FLOODSERV_ON            (unsigned int)885
#define CHAN_SET_FLOODSERV_OFF           (unsigned int)886

#define NUM_STRINGS 887
